' Developer Express Code Central Example:
' How to serialize DockLayoutManager using TabbedDocumentUIService
' 
' Some of DockLayoutManager’s panel groups can contain documents that were created
' from ViewModel with IDocumentManagerService. To serialize and restore them
' correctly, it is necessary to perform these steps:
' 
' 1. Create a style and set a
' name for DocumentPanel. To do this, bind DocumentPanel.BindableName to a unique
' property.
' 
' 2. Apply this style to all documents that will be created from
' ViewModel.
' 
' 3. Before serializing DockLayoutManager, serialize all documents
' created from ViewModel.
' 
' 4. Before restoring DockLayoutManager, recreate all
' documents created from ViewModel.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=T155653

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My


    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")> _
    Friend NotInheritable Partial Class Settings
        Inherits System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As Settings = (CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()), Settings))

        Public Shared ReadOnly Property [Default]() As Settings
            Get
                Return defaultInstance
            End Get
        End Property
    End Class
End Namespace
